services:
  db:
    image: postgres:15-alpine
    container_name: coliving_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=coliving_password
      - POSTGRES_DB=coliving_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: