[project]
name = "co-living-app"
version = "0.1.0"
description = "App for managig home budget, events, tasks and more"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.3",
    "uvicorn>=0.40.0",
]
